-- ============================================================
-- 06_views.sql - View for public trace API
-- ============================================================
-- View gom dữ liệu hay dùng khi khách quét QR.
-- Tác dụng: API đọc đơn giản, giảm lỗi field mismatch giữa DB và frontend.
-- ============================================================
CREATE OR REPLACE VIEW VW_PUBLIC_TRACE AS
SELECT
    P.PRODUCT_ID, P.BATCH_CODE, P.PRODUCT_NAME, P.CATEGORY, P.DESCRIPTION, P.QUALITY_SUMMARY,
    P.PRICE, P.QUANTITY, P.UNIT, P.STATUS AS PRODUCT_STATUS, P.VERSION_NO, P.IMAGE_URL,
    F.FARM_ID, F.FARM_NAME, F.ADDRESS AS FARM_ADDRESS, F.OWNER_NAME, F.CERTIFICATION,
    O.CULTIVATION_PLACE, O.SOWING_DATE, O.HARVEST_DATE, O.EXPIRED_DATE, O.PRODUCTION_PROCESS,
    Q.QR_TOKEN, Q.QR_SIGNATURE, Q.QR_URL, Q.STATUS AS QR_STATUS,
    Q.SALE_STATUS AS QR_SALE_STATUS, Q.SOLD_AT, Q.SOLD_BY_STORE_ID, Q.SOLD_NOTE,
    CASE
        WHEN O.EXPIRED_DATE IS NULL THEN 'UNKNOWN'
        WHEN O.EXPIRED_DATE < TRUNC(SYSDATE) THEN 'EXPIRED'
        WHEN O.EXPIRED_DATE - TRUNC(SYSDATE) <= 2 THEN 'NEAR_EXPIRED'
        ELSE 'FRESH'
    END AS FRESHNESS_STATUS
FROM PRODUCTS P
JOIN FARMS F ON P.FARM_ID = F.FARM_ID
LEFT JOIN PRODUCT_ORIGIN O ON P.PRODUCT_ID = O.PRODUCT_ID
LEFT JOIN QR_CODES Q ON P.PRODUCT_ID = Q.PRODUCT_ID;
