-- ============================================================
-- 07_indexes.sql - Performance indexes
-- ============================================================
-- Các index này phục vụ 3 truy vấn quan trọng nhất:
-- 1) Truy xuất QR theo token.
-- 2) Lấy timeline vận chuyển/lịch sử theo product_id + thời gian.
-- 3) Đếm scan trong ngày và tìm audit log.
-- ============================================================
CREATE INDEX IDX_PRODUCTS_FARM ON PRODUCTS(FARM_ID);
CREATE INDEX IDX_PRODUCTS_STATUS ON PRODUCTS(STATUS);
CREATE INDEX IDX_PRODUCTS_BATCH_CODE ON PRODUCTS(BATCH_CODE);
CREATE UNIQUE INDEX IDX_QR_TOKEN ON QR_CODES(QR_TOKEN);
CREATE INDEX IDX_QR_PRODUCT ON QR_CODES(PRODUCT_ID);
CREATE INDEX IDX_QR_STATUS ON QR_CODES(STATUS);
CREATE INDEX IDX_QR_SALE_STATUS ON QR_CODES(SALE_STATUS, SOLD_AT);
CREATE INDEX IDX_TRANSPORT_PRODUCT_TIME ON TRANSPORT_HISTORY(PRODUCT_ID, TRANSPORT_TIME);
CREATE INDEX IDX_STATUS_PRODUCT_TIME ON BATCH_STATUS_HISTORY(PRODUCT_ID, CHANGED_AT);
CREATE INDEX IDX_CERT_PRODUCT ON CERTIFICATES(PRODUCT_ID);
CREATE INDEX IDX_DIST_PRODUCT ON DISTRIBUTION_HISTORY(PRODUCT_ID);
CREATE INDEX IDX_SCAN_TOKEN_TIME ON QR_SCAN_LOGS(QR_TOKEN, SCANNED_AT);
CREATE INDEX IDX_SCAN_PRODUCT_TIME ON QR_SCAN_LOGS(PRODUCT_ID, SCANNED_AT);
CREATE INDEX IDX_ALERT_PRODUCT_TIME ON QR_SECURITY_ALERTS(PRODUCT_ID, CREATED_AT);
CREATE INDEX IDX_AUDIT_RECORD_TIME ON AUDIT_LOGS(RECORD_ID, CREATED_AT);
