-- ============================================================
-- 08_sample_data.sql - Minimal Oracle sample data
-- ============================================================
INSERT INTO FARMS(FARM_NAME, ADDRESS, OWNER_NAME, CERTIFICATION, CONTACT_PHONE, CONTACT_EMAIL)
VALUES('Trang trại Mật Vàng Đà Lạt', 'Đà Lạt, Lâm Đồng', 'Đặng Thu Hà', 'VietGAP 2026', '0901000001', 'dalat@honeybee.demo');

INSERT INTO TRANSPORTERS(TRANSPORTER_NAME, PHONE, ADDRESS, CONTACT_PERSON)
VALUES('BeeTruck Logistics', '0912000001', 'TP.HCM', 'Nguyễn Văn Tài');

INSERT INTO STORES(STORE_NAME, STORE_TYPE, ADDRESS, CITY, PHONE, CONTACT_PERSON)
VALUES('Honey Mart Quận 1', 'CLEAN_FOOD_STORE', 'Quận 1, TP.HCM', 'TP.HCM', '0923000001', 'Lê Thu Ngân');

INSERT INTO USERS(USERNAME, PASSWORD, FULL_NAME, EMAIL, ROLE, FARM_ID)
VALUES('farm1', '123456', 'Nông trại Mật Vàng', 'farm1@honeybee.demo', 'FARMER', 1);
INSERT INTO USERS(USERNAME, PASSWORD, FULL_NAME, EMAIL, ROLE)
VALUES('admin', 'admin123', 'Quản trị viên HoneyBee', 'admin@honeybee.demo', 'ADMIN');

INSERT INTO STATUS_TRANSITIONS(FROM_STATUS, TO_STATUS, ALLOWED_ROLE, DESCRIPTION) VALUES('CREATED','FARM_CONFIRMED','FARMER','Farm confirms origin');
INSERT INTO STATUS_TRANSITIONS(FROM_STATUS, TO_STATUS, ALLOWED_ROLE, DESCRIPTION) VALUES('FARM_CONFIRMED','CERTIFIED','ADMIN','Admin approves certificate');
INSERT INTO STATUS_TRANSITIONS(FROM_STATUS, TO_STATUS, ALLOWED_ROLE, DESCRIPTION) VALUES('CERTIFIED','READY_FOR_TRANSPORT','ADMIN','Ready for transport');

INSERT INTO PRODUCTS(FARM_ID, BATCH_CODE, PRODUCT_NAME, CATEGORY, QUALITY_SUMMARY, PRICE, QUANTITY, STATUS, CREATED_BY)
VALUES(1, 'HB-DL-RAU-001', 'Rau cải xanh HoneyBee', 'Rau xanh', 'Canh tác an toàn, bảo quản lạnh.', 32000, 120, 'CREATED', 1);

INSERT INTO PRODUCT_ORIGIN(PRODUCT_ID, CULTIVATION_PLACE, SOWING_DATE, HARVEST_DATE, EXPIRED_DATE, PRODUCTION_PROCESS)
VALUES(1, 'Nhà kính A1 - Đà Lạt', DATE '2026-04-10', DATE '2026-05-15', DATE '2026-05-20', 'Canh tác hữu cơ demo.');

INSERT INTO CERTIFICATES(FARM_ID, PRODUCT_ID, CERTIFICATE_NAME, ISSUED_BY, ISSUE_DATE, EXPIRED_DATE, STATUS)
VALUES(1, 1, 'VietGAP rau quả 2026', 'Trung tâm kiểm định Demo', DATE '2026-01-01', DATE '2026-12-31', 'VALID');

INSERT INTO QR_CODES(PRODUCT_ID, QR_TOKEN, QR_SIGNATURE, QR_URL, STATUS)
VALUES(1, 'HB-QR-RAU-001-SAFE', 'DEMO_SIGNATURE_SAFE', 'http://127.0.0.1:5500/product-detail.html?token=HB-QR-RAU-001-SAFE&sig=DEMO_SIGNATURE_SAFE', 'ACTIVE');

COMMIT;
