-- Lost Update - Session 1
-- Cả hai session đọc cùng VERSION_NO, sau đó update. Cách fix dùng WHERE VERSION_NO = version cũ.
SELECT PRODUCT_ID, STATUS, VERSION_NO FROM PRODUCTS WHERE PRODUCT_ID = 1;
UPDATE PRODUCTS
SET STATUS = 'FARM_CONFIRMED', VERSION_NO = VERSION_NO + 1
WHERE PRODUCT_ID = 1 AND VERSION_NO = 0;
COMMIT;
