-- Phantom Read - Session 2
INSERT INTO PRODUCTS(FARM_ID, BATCH_CODE, PRODUCT_NAME, CATEGORY, PRICE, QUANTITY, STATUS)
VALUES(1, 'HB-PHANTOM-TEST', 'Lô phantom test', 'Demo', 1, 1, 'AVAILABLE_FOR_SALE');
COMMIT;
