-- Phantom Read - Session 1
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SELECT COUNT(*) AS AVAILABLE_COUNT FROM PRODUCTS WHERE STATUS = 'AVAILABLE_FOR_SALE';
-- Sang session 2 INSERT một lô AVAILABLE_FOR_SALE + COMMIT.
SELECT COUNT(*) AS AVAILABLE_COUNT FROM PRODUCTS WHERE STATUS = 'AVAILABLE_FOR_SALE';
COMMIT;
