-- Execution plan: QR trace by token
-- Kỳ vọng sau index IDX_QR_TOKEN: Oracle dùng INDEX UNIQUE SCAN thay vì full table scan QR_CODES.
EXPLAIN PLAN FOR
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, F.FARM_NAME, Q.QR_TOKEN
FROM QR_CODES Q
JOIN PRODUCTS P ON Q.PRODUCT_ID = P.PRODUCT_ID
JOIN FARMS F ON P.FARM_ID = F.FARM_ID
WHERE Q.QR_TOKEN = 'HB-QR-RAU-001-SAFE';
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
